const data = [
  {
    "date": "1907-01-26",
    "country": "CZ",
    "CZtitle": "Volební právo mužů",
    "CZdescription": "26. ledna 1907 – všeobecné a rovné vol. právo mužů",
    "ENtitle": "Male Suffrage",
    "ENdescription": "January 26, 1907 – universal and equal voting rights for men",
    "DEtitle": "Männerwahlrecht",
    "DEdescription": "26. Januar 1907 – allgemeines und gleiches Wahlrecht für Männer",
    "url": "male-suffrage"
  },
  {
    "date": "1914-07-25",
    "country": "CZ",
    "CZtitle": "Stanné právo",
    "CZdescription": "25. července 1914 – vyhlášení stanného práva po atentátu na nástupce trůnu, omezení základních svobod",
    "ENtitle": "Martial Law",
    "ENdescription": "July 25, 1914 – declaration of martial law after the assassination of the heir to the throne, restriction of basic freedoms",
    "DEtitle": "Standrecht",
    "DEdescription": "25. Juli 1914 – Verkündung des Standrechts nach dem Attentat auf den Thronfolger, Einschränkung der Grundfreiheiten",
    "url": "martial-law"
  },
  {
    "date": "1917-07-02",
    "country": "CZ",
    "CZtitle": "Zrušení pol. procesů",
    "CZdescription": "2. července 1917 – zrušení politických procesů",
    "ENtitle": "Abolition of Political Trials",
    "ENdescription": "July 2, 1917 – the abolition of political trials",
    "DEtitle": "Abschaffung politischer Prozesse",
    "DEdescription": "2. Juli 1917 – Aufhebung politischer Prozesse",
    "url": "abolition-of-political-trials"
  },
  {
    "date": "1918-10-28",
    "country": "CZ",
    "CZtitle": "Vznik ČSR",
    "CZdescription": "28. říjen 1918 – vznik samostatné Československé republiky",
    "ENtitle": "Formation of Czechoslovakia",
    "ENdescription": "October 28, 1918 – the establishment of the independent Czechoslovak Republic",
    "DEtitle": "Gründung der Tschechoslowakei",
    "DEdescription": "28. Oktober 1918 – Gründung der unabhängigen Tschechoslowakischen Republik",
    "url": "formation-of-czechoslovakia"
  },
  {
    "date": "1918-11-13",
    "country": "CZ",
    "CZtitle": "Prozatímní ústava",
    "CZdescription": "13. listopad 1918 – schválení prozatímní ústavy (vol. právo žen)",
    "ENtitle": "Interim Constitution",
    "ENdescription": "November 13, 1918 – approval of the interim constitution (women's suffrage)",
    "DEtitle": "Übergangsverfassung",
    "DEdescription": "13. November 1918 – Verabschiedung der Übergangsverfassung (Frauenwahlrecht)",
    "url": "interim-constitution"
  },
  {
    "date": "1918-11-14",
    "country": "CZ",
    "CZtitle": "Rev. národní shromáždění",
    "CZdescription": "14. listopad 1918 – vznik Revolučního národního shromáždění, Masaryk prezidentem",
    "ENtitle": "Rev. National Assembly",
    "ENdescription": "November 14, 1918 – establishment of the Revolutionary National Assembly, Masaryk as president",
    "DEtitle": "Rev. Nationalversammlung",
    "DEdescription": "14. November 1918 – Gründung der Revolutionären Nationalversammlung, Masaryk zum Präsidenten",
    "url": "revolutionary-national-assembly"
  },
  {
    "date": "1918-12-19",
    "country": "CZ",
    "CZtitle": "8h pracovní doba",
    "CZdescription": "19. prosince 1918 – zákon o osmihodinové pracovní době",
    "ENtitle": "8-hour Work Day",
    "ENdescription": "December 19, 1918 – the eight-hour working day law",
    "DEtitle": "8-Stunden-Arbeitstag",
    "DEdescription": "19. Dezember 1918 – Gesetz über den Achtstundentag",
    "url": "8-hour-work-day"
  },
  {
    "date": "1919-06-15",
    "country": "CZ",
    "CZtitle": "Komunální volby",
    "CZdescription": "15. června 1919 – komunální volby, ženy mohou poprvé volit a být voleny",
    "ENtitle": "Local Elections",
    "ENdescription": "June 15, 1919 – local elections, women can vote and be elected for the first time",
    "DEtitle": "Kommunalwahlen",
    "DEdescription": "15. Juni 1919 – Kommunalwahlen, Frauen dürfen zum ersten Mal wählen und gewählt werden",
    "url": "local-elections-women"
  },
  {
    "date": "1920-01-30",
    "country": "CZ",
    "CZtitle": "Pozemková reforma",
    "CZdescription": "30. ledna 1920 – zákon o pozemkové reformě (omezení velkostatkářství)",
    "ENtitle": "Land Reform",
    "ENdescription": "January 30, 1920 – land reform law (limitation of large estates)",
    "DEtitle": "Bodenreform",
    "DEdescription": "30. Januar 1920 – Gesetz zur Bodenreform (Beschränkung des Großgrundbesitzes)",
    "url": "land-reform"
  },
  {
    "date": "1920-02-29",
    "country": "CZ",
    "CZtitle": "Finální ústava (rovnost žen)",
    "CZdescription": "29. února 1920 – schválení finální ústavy ČSR (rovnoprávnost žen)",
    "ENtitle": "Final Constitution",
    "ENdescription": "February 29, 1920 – approval of the final constitution of Czechoslovakia (equality of women)",
    "DEtitle": "Endgültige Verfassung",
    "DEdescription": "29. Februar 1920 – Verabschiedung der endgültigen Verfassung der ČSR (Gleichberechtigung der Frauen)",
    "url": "final-constitution"
  },
  {
    "date": "1920-04-18",
    "country": "CZ",
    "CZtitle": "Volby do posl. sněmovny",
    "CZdescription": "18. dubna 1920 – volby do poslanecké sněmovny",
    "ENtitle": "Chamber of Deputies Elections",
    "ENdescription": "April 18, 1920 – elections to the Chamber of Deputies",
    "DEtitle": "Abgeordnetenhauswahlen",
    "DEdescription": "18. April 1920 – Wahlen zum Abgeordnetenhaus",
    "url": "chamber-of-deputies-elections"
  },
  {
    "date": "1920-04-25",
    "country": "CZ",
    "CZtitle": "Volby do senátu",
    "CZdescription": "25. dubna 1920 – volby do senátu",
    "ENtitle": "Senate Elections",
    "ENdescription": "April 25, 1920 – elections to the Senate",
    "DEtitle": "Senatswahlen",
    "DEdescription": "25. April 1920 – Wahlen zum Senat",
    "url": "senate-elections"
  },
  {
    "date": "1920-05-27",
    "country": "CZ",
    "CZtitle": "Konec Rev. nár. shrom.",
    "CZdescription": "27. května 1920 – konec činnosti Revolučního národního shromáždění",
    "ENtitle": "End of Rev. National Assembly",
    "ENdescription": "May 27, 1920 – termination of the activities of the Revolutionary National Assembly",
    "DEtitle": "Rev. Nationalversammlung Ende",
    "DEdescription": "27. Mai 1920 – Ende der Tätigkeit der Revolutionären Nationalversammlung",
    "url": "end-of-rev-national-assembly"
  },
  {
    "date": "1921-10-22",
    "country": "CZ",
    "CZtitle": "Soc. pojištění dělníků",
    "CZdescription": "22. října 1921 – zákon o sociálním pojištění dělníků",
    "ENtitle": "Workers' Social Insurance",
    "ENdescription": "October 22, 1921 – law on social insurance for workers",
    "DEtitle": "Sozialversicherung für Arbeiter",
    "DEdescription": "22. Oktober 1921 – Gesetz über die Sozialversicherung der Arbeiter",
    "url": "workers-social-insurance"
  },
  {
    "date": "1923-03-19",
    "country": "CZ",
    "CZtitle": "Omezení extrem. stran",
    "CZdescription": "19. března 1923 – zákon na ochranu republiky (omezení extremistických stran)",
    "ENtitle": "Restriction of Extremist Parties",
    "ENdescription": "March 19, 1923 – Act for the Protection of the Republic (restriction of extremist parties)",
    "DEtitle": "Einschränkung extremistischer Parteien",
    "DEdescription": "19. März 1923 – Gesetz zum Schutz der Republik (Einschränkung extremistischer Parteien)",
    "url": "restriction-of-extremist-parties"
  },
  {
    "date": "1933-10-04",
    "country": "CZ",
    "CZtitle": "Zákaz nacistické strany",
    "CZdescription": "4. října 1933 – rozpuštění nacistické strany DNSAP v ČSR",
    "ENtitle": "Ban on Nazi Party",
    "ENdescription": "October 4, 1933 – dissolution of the DNSAP Nazi party in Czechoslovakia",
    "DEtitle": "Verbot der Nazipartei",
    "DEdescription": "4. Oktober 1933 – Auflösung der Nazi-Partei DNSAP in der ČSR",
    "url": "ban-on-nazi-party"
  },
  {
    "date": "1935-12-18",
    "country": "CZ",
    "CZtitle": "Beneš prezidentem",
    "CZdescription": "18. prosince 1935 – Edvard Beneš zvolen prezidentem",
    "ENtitle": "Beneš as President",
    "ENdescription": "December 18, 1935 – Edvard Beneš elected president",
    "DEtitle": "Beneš als Präsident",
    "DEdescription": "18. Dezember 1935 – Edvard Beneš zum Präsidenten gewählt",
    "url": "benes-as-president"
  },
  {
    "date": "1936-05-13",
    "country": "CZ",
    "CZtitle": "Zákon o obraně státu",
    "CZdescription": "13. května 1936 – zákon o obraně státu (reakce na nacistickou hrozbu)",
    "ENtitle": "State Defense Act",
    "ENdescription": "May 13, 1936 – State Defense Act (reaction to the Nazi threat)",
    "DEtitle": "Staatsverteidigungsgesetz",
    "DEdescription": "13. Mai 1936 – Staatsverteidigungsgesetz (Reaktion auf die Bedrohung durch die Nazis)",
    "url": "state-defense-act"
  },


  {
    "date": "1914-07-31",
    "country": "DE",
    "CZtitle": "Cenzura a omezení svobod",
    "CZdescription": "31. července 1914 – cenzura tisku a omezení shromažďování po vyhlášení válečného stavu",
    "ENtitle": "Censorship and Restriction of Freedoms",
    "ENdescription": "July 31, 1914 – press censorship and restriction of assembly after the declaration of martial law",
    "DEtitle": "Zensur und Einschränkung der Freiheiten",
    "DEdescription": "31. Juli 1914 – Pressezensur und Versammlungsbeschränkungen nach der Ausrufung des Kriegszustands",
    "url": "censorship-and-restriction-of-freedoms"
  },
  {
    "date": "1916-08-29",
    "country": "DE",
    "CZtitle": "Vojenská diktatura",
    "CZdescription": "29. srpna 1916 – Hindenburg a Ludendorff přebírají faktickou moc (vojenská diktatura)",
    "ENtitle": "Military Dictatorship",
    "ENdescription": "August 29, 1916 – Hindenburg and Ludendorff take factual power (military dictatorship)",
    "DEtitle": "Militärdiktatur",
    "DEdescription": "29. August 1916 – Hindenburg und Ludendorff übernehmen die faktische Macht (Militärdiktatur)",
    "url": "military-dictatorship"
  },
  {
    "date": "1918-01-28",
    "country": "DE",
    "CZtitle": "Stávky dělníků za svobodu",
    "CZdescription": "od 28. ledna 1918 – masové stávky dělníků za mír a politické svobody",
    "ENtitle": "Workers' Strikes for Freedom",
    "ENdescription": "From January 28, 1918 – mass strikes by workers for peace and political freedoms",
    "DEtitle": "Arbeiterstreiks für die Freiheit",
    "DEdescription": "Ab dem 28. Januar 1918 – Massenstreiks der Arbeiter für Frieden und politische Freiheiten",
    "url": "workers-strikes-for-freedom"
  },
  {
    "date": "1918-11-09",
    "country": "DE",
    "CZtitle": "Vyhlášení republiky",
    "CZdescription": "9. listopadu 1918 – abdikace Viléma II., vyhlášení republiky",
    "ENtitle": "Proclamation of the Republic",
    "ENdescription": "November 9, 1918 – abdication of Wilhelm II, proclamation of the republic",
    "DEtitle": "Ausrufung der Republik",
    "DEdescription": "9. November 1918 – Abdankung Wilhelms II., Ausrufung der Republik",
    "url": "proclamation-of-the-republic"
  },
  {
    "date": "1918-11-12",
    "country": "DE",
    "CZtitle": "8h pracovní doba",
    "CZdescription": "12. listopadu 1918 – zavedení 8hodinové pracovní doby",
    "ENtitle": "8-hour Work Day",
    "ENdescription": "November 12, 1918 – introduction of the 8-hour working day",
    "DEtitle": "8-Stunden-Arbeitstag",
    "DEdescription": "12. November 1918 – Einführung des 8-Stunden-Arbeitstages",
    "url": "8-hour-work-day-de"
  },
  {
    "date": "1919-01-05",
    "country": "DE",
    "CZtitle": "Povstání spartakovců",
    "CZdescription": "5. - 15. ledna 1919 – potlačení Spartakovského povstání, zavraždění Karla Liebknechta a Rosy Luxemburgové",
    "ENtitle": "Spartacist Uprising",
    "ENdescription": "January 5–15, 1919 – suppression of the Spartacist uprising, assassination of Karl Liebknecht and Rosa Luxemburg",
    "DEtitle": "Spartakusaufstand",
    "DEdescription": "5.–15. Januar 1919 – Niederschlagung des Spartakusaufstands, Ermordung von Karl Liebknecht und Rosa Luxemburg",
    "url": "spartacist-uprising"
  },
  {
    "date": "1919-01-19",
    "country": "DE",
    "CZtitle": "Volby vč. žen",
    "CZdescription": "19. ledna 1919 – volby do Výmarského nár. shromáždění (i ženy)",
    "ENtitle": "Elections including Women",
    "ENdescription": "January 19, 1919 – elections to the Weimar National Assembly (including women)",
    "DEtitle": "Wahlen einschließlich Frauen",
    "DEdescription": "19. Januar 1919 – Wahlen zur Weimarer Nationalversammlung (einschließlich Frauen)",
    "url": "elections-including-women"
  },
  {
    "date": "1919-08-11",
    "country": "DE",
    "CZtitle": "Výmarská ústava",
    "CZdescription": "11. srpna 1919 – přijetí Výmarské ústavy (základní občanská práva)",
    "ENtitle": "Weimar Constitution",
    "ENdescription": "August 11, 1919 – adoption of the Weimar Constitution (fundamental civil rights)",
    "DEtitle": "Weimarer Verfassung",
    "DEdescription": "11. August 1919 – Verabschiedung der Weimarer Verfassung (Grundrechte)",
    "url": "weimar-constitution"
  },
  {
    "date": "1920-01-18",
    "country": "DE",
    "CZtitle": "Závodní rady",
    "CZdescription": "18. ledna 1920 – zákon o závodních radách (zastoupení dělníků)",
    "ENtitle": "Works Councils",
    "ENdescription": "January 18, 1920 – Works Councils Act (worker representation)",
    "DEtitle": "Betriebsräte",
    "DEdescription": "18. Januar 1920 – Betriebsrätegesetz (Arbeitnehmervertretung)",
    "url": "works-councils"
  },
  {
    "date": "1933-01-30",
    "country": "DE",
    "CZtitle": "Hitler kancléřem",
    "CZdescription": "30. ledna 1933 – Hitler jmenován říšským kancléřem",
    "ENtitle": "Hitler as Chancellor",
    "ENdescription": "January 30, 1933 – Hitler appointed Reich Chancellor",
    "DEtitle": "Hitler als Reichskanzler",
    "DEdescription": "30. Januar 1933 – Hitler wird zum Reichskanzler ernannt",
    "url": "hitler-as-chancellor"
  },
  {
    "date": "1933-02-27",
    "country": "DE",
    "CZtitle": "Požár Reichstagu",
    "CZdescription": "27. února 1933 – požár Reichstagu",
    "ENtitle": "Reichstag Fire",
    "ENdescription": "February 27, 1933 – Reichstag fire",
    "DEtitle": "Reichstagsbrand",
    "DEdescription": "27. Februar 1933 – Reichstagsbrand",
    "url": "reichstag-fire"
  },
  {
    "date": "1933-02-28",
    "country": "DE",
    "CZtitle": "Zrušení občanských svobod",
    "CZdescription": "28. února 1933 – Hindenburgův dekret o zrušení základních občanských svobod",
    "ENtitle": "Abolition of Civil Liberties",
    "ENdescription": "February 28, 1933 – Hindenburg Decree on the abolition of fundamental civil liberties",
    "DEtitle": "Abschaffung der bürgerlichen Freiheiten",
    "DEdescription": "28. Februar 1933 – Hindenburg-Dekret über die Aufhebung der bürgerlichen Grundrechte",
    "url": "abolition-of-civil-liberties"
  },
  {
    "date": "1933-03-23",
    "country": "DE",
    "CZtitle": "Zmocňovací zákon",
    "CZdescription": "23. března 1933 – zmocňovací zákon, konec parlamentní demokracie",
    "ENtitle": "Enabling Act",
    "ENdescription": "March 23, 1933 – Enabling Act, end of parliamentary democracy",
    "DEtitle": "Ermächtigungsgesetz",
    "DEdescription": "23. März 1933 – Ermächtigungsgesetz, Ende der parlamentarischen Demokratie",
    "url": "enabling-act"
  },
  {
    "date": "1933-02-29",
    "country": "DE",
    "CZtitle": "Zákaz odborů a opozice",
    "CZdescription": "28. února – 14. července 1933 – zákaz odborů a opozičních stran",
    "ENtitle": "Ban on Unions and Opposition",
    "ENdescription": "February 28 – July 14, 1933 – ban on trade unions and opposition parties",
    "DEtitle": "Gewerksch. und Opposit. Verbot",
    "DEdescription": "28. Februar – 14. Juli 1933 – Verbot von Gewerkschaften und Oppositionsparteien",
    "url": "ban-on-unions-and-opposition"
  },
  {
    "date": "1934-06-30",
    "country": "DE",
    "CZtitle": "Noc dlouhých nožů",
    "CZdescription": "30. června – 2. července 1934 – Noc dlouhých nožů, likvidace vnitřní opozice",
    "ENtitle": "Night of the Long Knives",
    "ENdescription": "June 30 – July 2, 1934 – Night of the Long Knives, elimination of internal opposition",
    "DEtitle": "Nacht der langen Messer",
    "DEdescription": "30. Juni – 2. Juli 1934 – Nacht der langen Messer, Liquidierung der internen Opposition",
    "url": "night-of-the-long-knives"
  },
  {
    "date": "1934-08-02",
    "country": "DE",
    "CZtitle": "Hitler Führerem",
    "CZdescription": "2. srpna 1934 – smrt Hindenburga, Hitler spojuje funkce kancléře a prezidenta",
    "ENtitle": "Hitler as Fuhrer",
    "ENdescription": "August 2, 1934 – death of Hindenburg, Hitler combines the offices of chancellor and president",
    "DEtitle": "Hitler als Führer",
    "DEdescription": "2. August 1934 – Hindenburgs Tod, Hitler vereint die Ämter des Kanzlers und des Präsidenten",
    "url": "hitler-as-fuhrer"
  },
  {
    "date": "1935-09-15",
    "country": "DE",
    "CZtitle": "Norimberské zákony",
    "CZdescription": "15. září 1935 – Norimberské zákony (rasová diskriminace Židů)",
    "ENtitle": "Nuremberg Laws",
    "ENdescription": "September 15, 1935 – Nuremberg Laws (racial discrimination of Jews)",
    "DEtitle": "Nürnberger Gesetze",
    "DEdescription": "15. September 1935 – Nürnberger Gesetze (Rassendiskriminierung von Juden)",
    "url": "nuremberg-laws"
  },
  {
    "date": "1938-03-12",
    "country": "DE",
    "CZtitle": "Anschluss Rakouska",
    "CZdescription": "12. března 1938 – anexe Rakouska",
    "ENtitle": "Anschluss of Austria",
    "ENdescription": "March 12, 1938 – annexation of Austria",
    "DEtitle": "Anschluss Österreichs",
    "DEdescription": "12. März 1938 – Anschluss Österreichs",
    "url": "anschluss-of-austria"
  },
  {
    "date": "1938-11-09",
    "country": "DE",
    "CZtitle": "Křišťálová noc",
    "CZdescription": "9.–10. listopadu 1938 – Křišťálová noc, pogromy na Židy",
    "ENtitle": "Kristallnacht",
    "ENdescription": "November 9–10, 1938 – Kristallnacht, pogroms against Jews",
    "DEtitle": "Kristallnacht",
    "DEdescription": "9.–10. November 1938 – Kristallnacht, Pogrome gegen Juden",
    "url": "kristallnacht-de"
  },

  
  {
    "date": "1939-03-14",
    "country": "CZ",
    "CZtitle": "Odtržení Slovenska",
    "CZdescription": "14. března 1939 – vyhlášení samostatného Slovenského štátu",
    "ENtitle": "Secession of Slovakia",
    "ENdescription": "March 14, 1939 – declaration of the independent Slovak State",
    "DEtitle": "Abspaltung der Slowakei",
    "DEdescription": "14. März 1939 – Ausrufung des unabhängigen slowakischen Staates",
    "url": "secession-of-slovakia"
  },
  {
    "date": "1939-03-15",
    "country": "CZ",
    "CZtitle": "Okupace, konec ČSR",
    "CZdescription": "15. března 1939 – okupace zbytku Čech a Moravy, konec demokratické ČSR",
    "ENtitle": "Occupation, end of CSR",
    "ENdescription": "March 15, 1939 – occupation of the rest of Bohemia and Moravia, end of democratic Czechoslovakia",
    "DEtitle": "Besatzung, Ende der ČSR",
    "DEdescription": "15. März 1939 – Besetzung der restlichen böhmischen und mährischen Gebiete, Ende der demokratischen ČSR",
    "url": "occupation-end-of-csr"
  }
];